import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

const kanit = Kanit({
  weight: ["400", "500", "700"],
  subsets: ["latin", "thai"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "C-VOICE",
  // TODO: Provide a good OG description!
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} flex flex-col h-full min-h-screen font-sans`}
      >
        <Navbar />
        <main className="flex-1 flex flex-col flex-grow p-8 relative">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
